### ISSUE TITLE
Using Robust Video Matting with Canvas 2D vs WebGL2

### ISSUE THREAD

**Issue by edamlmmv** [vladmandic/segmentation#1]
Is there a specific reason why you used Canvas 2D instead of WebGL2 to draw the original video and processed output onto the canvas? Would it be possible to use WebGL2 as it is faster? I'll try on my side and do a PR if I find something conclusive.
<img width="993" alt="Screenshot 2023-12-31 at 2 05 42 PM" src="https://github.com/vladmandic/segmentation/assets/90264844/e7e66e7a-303d-44f9-b08b-bf5faa2cdc68">

**Comment by vladmandic** [comment]
> Is there a specific reason why you used Canvas 2D instead of WebGL2 to draw the original video and processed output onto the canvas? Would it be possible to use WebGL2 as it is faster? I'll try on my side and do a PR if I find something conclusive.

yes, it would be possible.
but drawing composite image on canvas using webgl is cumbersome and performance benefits are not as huge as you might think - i just don't consider it as critical item for a showcase repo.
